"""Shared deterministic Markdown rendering for bilingual page artifacts."""

from __future__ import annotations

from typing import Any


def quote_block(text: str) -> str:
    return "\n".join("> " + line if line else ">" for line in text.splitlines()) or "> "


def render_page_markdown(page: dict[str, Any]) -> str:
    page_number = page["page"]
    source_text = str(page.get("text", "")).strip()
    translation = str(page.get("translation", "")).strip()
    return "\n".join(
        [
            f"#### Slide {page_number} · 逐页中英对照",
            "",
            "> [!quote] English / 英文",
            quote_block(source_text or "No translatable text on this page"),
            "",
            "> [!note] Chinese / 中文",
            quote_block(translation or "本页无可翻译文字"),
        ]
    ).rstrip() + "\n"


def render_markdown(payload: dict[str, Any]) -> str:
    sections = ["<!-- Generated by local Argos Translate; selectively reviewed. -->"]
    sections.extend(render_page_markdown(page).rstrip() for page in payload["pages"])
    return "\n\n".join(sections).rstrip() + "\n"
